-- Player-facing director controls.
return {
    director_fixed_map_seed={en="Use a fixed roamer-layout seed",["zh-cn"]="启用固定驻军布局种子",["zh-tw"]="啟用固定駐軍佈局種子"},
    director_fixed_director_seed={en="Use a fixed HED director seed",["zh-cn"]="启用固定 HED 导演种子",["zh-tw"]="啟用固定 HED 導演種子"},
    director_overview={en="Director",["zh-cn"]="导演总览",["zh-tw"]="導演總覽"},
    director_formations={en="Formation library",["zh-cn"]="编队库",["zh-tw"]="編隊庫"},
    director_deployments={en="Deployment rules",["zh-cn"]="投放规则",["zh-tw"]="投放規則"},
    director_native={en="Native templates",["zh-cn"]="原版模板",["zh-tw"]="原版模板"},
    director_presets={en="Presets & changes",["zh-cn"]="方案与变更",["zh-tw"]="方案與變更"},
    director_general={en="Run settings",["zh-cn"]="运行设置",["zh-tw"]="執行設定"},
    director_pressure={en="Pressure phases",["zh-cn"]="压力阶段",["zh-tw"]="壓力階段"},
    director_seeds={en="Random seeds",["zh-cn"]="随机种子",["zh-tw"]="隨機種子"},
    director_summary={en="Configuration summary",["zh-cn"]="配置摘要",["zh-tw"]="配置摘要"},
    director_enabled={en="Enable extra encounters",["zh-cn"]="启用额外编队导演",["zh-tw"]="啟用額外編隊導演"},
    director_mode={en="Director mode",["zh-cn"]="导演模式",["zh-tw"]="導演模式"},
    director_rules={en="Rule-driven",["zh-cn"]="按投放规则运行",["zh-tw"]="按投放規則執行"},
    director_adaptive={en="Adaptive pressure",["zh-cn"]="根据压力自适应",["zh-tw"]="根據壓力自適應"},
    director_selection={en="Competing rules",["zh-cn"]="多条规则同时满足时",["zh-tw"]="多條規則同時滿足時"},
    director_priority={en="Priority, then weight",["zh-cn"]="先比优先级，再按权重抽取",["zh-tw"]="先比優先順序，再按權重抽取"},
    director_weighted={en="Weight only",["zh-cn"]="直接按权重抽取",["zh-tw"]="直接按權重抽取"},
    director_admission_interval={en="Minimum gap between admissions (s)",["zh-cn"]="全局两次接纳间隔（秒）",["zh-tw"]="全域性兩次接納間隔（秒）"},
    director_max_active_groups={en="Maximum active HED encounters",["zh-cn"]="HED 同时活跃遭遇上限",["zh-tw"]="HED 同時活躍遭遇上限"},
    director_load_ceiling={en="Hold new arrivals at combat load",["zh-cn"]="暂缓新增敌人的战斗负担门槛",["zh-tw"]="暫緩新增敵人的戰鬥負擔門檻"},
    director_capable_min={en="Minimum capable players",["zh-cn"]="至少需要的有效玩家人数",["zh-tw"]="至少需要的有效玩家人數"},
    director_allow_events={en="Allow arrivals during mission events",["zh-cn"]="允许在任务事件期间额外投放",["zh-tw"]="允許在任務事件期間額外投放"},
    director_status_help={en="Changes are saved for the next mission. Native spawns still run. HED adds only encounters referenced by enabled deployment rules.",["zh-cn"]="修改保存后于下一局生效。原版刷怪继续运行；HED 只额外安排已启用规则所引用的编队。",["zh-tw"]="修改儲存後於下一局生效。原版刷怪繼續執行；HED 只額外安排已啟用規則所引用的編隊。"},
    director_empty_help={en="Start with a formation, then add a deployment rule. Finally enable the director. Templates and HCM multipliers can also be used on their own.",["zh-cn"]="先在编队库选择敌人，再建立投放规则，最后启用导演。原版模板编辑和 HCM 倍率也可以单独使用。",["zh-tw"]="先在編隊庫選擇敵人，再建立投放規則，最後啟用導演。原版模板編輯和 HCM 倍率也可以單獨使用。"},
    director_limits_help={en="Pending and living encounters both occupy this limit. Native permissions, enemy capacity and valid spawn positions can delay an arrival.",["zh-cn"]="待生成与仍有存活成员的遭遇都会占用额度。原版刷怪许可、敌人容量与有效出生位置仍可能延后到场。",["zh-tw"]="待生成與仍有存活成員的遭遇都會佔用額度。原版刷怪許可、敵人容量與有效出生位置仍可能延後到場。"},
    director_phase_help={en="Adaptive mode cycles through build, pressure and recovery. High load or too few capable players starts recovery early. Recovery waits for its minimum duration and low load.",["zh-cn"]="自适应模式依次经历蓄压、施压、恢复。战斗负担过高或有效玩家过少会提前恢复；恢复须满足最低时长与低负担条件才会结束。",["zh-tw"]="自適應模式依次經歷蓄壓、施壓、恢復。戰鬥負擔過高或有效玩家過少會提前恢復；恢復須滿足最低時長與低負擔條件才會結束。"},
    director_build={en="Build",["zh-cn"]="蓄压",["zh-tw"]="蓄壓"},
    director_pressure_phase={en="Pressure",["zh-cn"]="施压",["zh-tw"]="施壓"},
    director_recovery={en="Recovery",["zh-cn"]="恢复",["zh-tw"]="恢復"},
    director_any={en="Any phase",["zh-cn"]="不限阶段",["zh-tw"]="不限階段"},
    director_low_load={en="Leave recovery below this load",["zh-cn"]="结束恢复所需的低负担门槛",["zh-tw"]="結束恢復所需的低負擔門檻"},
    director_high_load={en="Enter recovery at this load",["zh-cn"]="提前进入恢复的高负担门槛",["zh-tw"]="提前進入恢復的高負擔門檻"},
    director_duration_min={en="Minimum phase duration (s)",["zh-cn"]="阶段最短时长（秒）",["zh-tw"]="階段最短時長（秒）"},
    director_duration_max={en="Maximum phase duration (s)",["zh-cn"]="阶段最长时长（秒）",["zh-tw"]="階段最長時長（秒）"},
    director_phase_size={en="Encounter size in this phase",["zh-cn"]="本阶段人数倍率",["zh-tw"]="本階段人數倍率"},
    director_phase_frequency={en="Arrival frequency; 0 pauses HED",["zh-cn"]="本阶段频率倍率；0 为暂停",["zh-tw"]="本階段頻率倍率；0 為暫停"},
    director_phase_only={en="These settings apply in Adaptive pressure mode.",["zh-cn"]="这些设置仅在自适应模式中参与运行。",["zh-tw"]="這些設定僅在自適應模式中參與執行。"},
    director_director_seed={en="HED director seed",["zh-cn"]="HED 导演种子",["zh-tw"]="HED 導演種子"},
    director_map_seed={en="Roamer-layout seed",["zh-cn"]="驻军布局种子",["zh-tw"]="駐軍佈局種子"},
    director_auto_seed={en="Use the mission seed",["zh-cn"]="沿用任务种子",["zh-tw"]="沿用任務種子"},
    director_seed_help={en="Off uses the mission seed. On uses the full integer entered here (1–2147483646). HED keeps separate streams for phase changes, deployment selection, timers, formation variants and member counts.",["zh-cn"]="关闭时使用本局任务种子；开启时使用输入的完整整数（1–2147483646）。HED 分别为阶段切换、部署抽选、间隔、编队变体和成员数量维护随机流。",["zh-tw"]="關閉時使用本局任務種子；開啟時使用輸入的完整整數（1–2147483646）。HED 分別為階段切換、部署抽選、間隔、編隊變體和成員數量維護隨機流。"},
    director_map_seed_help={en="Off preserves the native mission layout seed. On replaces only the native roamer-layout seed. This does not change the mission map or control every native combat random process.",["zh-cn"]="关闭时沿用原生任务布局种子；开启时仅替换原生驻军布局种子。它不改变任务地图，也不控制所有原生战斗随机过程。",["zh-tw"]="關閉時沿用原生任務佈局種子；開啟時僅替換原生駐軍佈局種子。它不改變任務地圖，也不控制所有原生戰鬥隨機過程。"},
    director_seed_limit={en="Switches keep their saved numbers when off. Changes apply next mission. Matching seeds reproduce choices only with matching inputs; movement, native combat and spawn locations can still change outcomes.",["zh-cn"]="关闭开关会保留输入值，修改用于下一局。相同种子还需相同输入才能复现随机选择；玩家移动、原生战斗和生成位置仍会影响结果。",["zh-tw"]="關閉開關會保留輸入值，修改用於下一局。相同種子還需相同輸入才能復現隨機選擇；玩家移動、原生戰鬥和生成位置仍會影響結果。"},
    director_seed_reset={en="Set to automatic",["zh-cn"]="恢复自动种子",["zh-tw"]="恢復自動種子"},
    director_counts={en="%d formations · %d deployment rules",["zh-cn"]="%d 个编队 · %d 条投放规则",["zh-tw"]="%d 個編隊 · %d 條投放規則"},
    director_overrides={en="%d fixed values · %d relative multipliers · %d native rules",["zh-cn"]="%d 项固定值 · %d 项相对倍率 · %d 条原版规则",["zh-tw"]="%d 項固定值 · %d 項相對倍率 · %d 條原版規則"},
    director_no_formations={en="No formations yet. Choose an enemy category and create one.",["zh-cn"]="还没有编队。选择敌人类别并创建编队。",["zh-tw"]="還沒有編隊。選擇敵人類別並建立編隊。"},
    director_no_deployments={en="No deployment rules yet. Create a formation first, then choose it here.",["zh-cn"]="还没有投放规则。先创建编队，再在这里选择要调用的编队。",["zh-tw"]="還沒有投放規則。先建立編隊，再在這裡選擇要呼叫的編隊。"},
    director_new_family={en="Category for a new formation",["zh-cn"]="新编队的敌人类别",["zh-tw"]="新編隊的敵人類別"},
    director_add_formation={en="Create formation",["zh-cn"]="创建编队",["zh-tw"]="建立編隊"},
    director_add_deployment={en="Create deployment rule",["zh-cn"]="创建投放规则",["zh-tw"]="建立投放規則"},
    director_new_formation={en="Formation %d",["zh-cn"]="编队 %d",["zh-tw"]="編隊 %d"},
    director_new_deployment={en="Deployment %d",["zh-cn"]="投放 %d",["zh-tw"]="投放 %d"},
    director_name={en="Name",["zh-cn"]="名称",["zh-tw"]="名稱"},
    director_save={en="Save",["zh-cn"]="保存",["zh-tw"]="儲存"},
    director_name_hint={en="Up to 48 characters. Enter saves; Escape cancels.",["zh-cn"]="最多 48 个字符。回车保存，Esc 取消。",["zh-tw"]="最多 48 個字元。回車儲存，Esc 取消。"},
    director_invalid_name={en="Enter a name of 1–48 characters without control characters.",["zh-cn"]="请输入 1～48 个字符的名称，不含控制字符。",["zh-tw"]="請輸入 1～48 個字元的名稱，不含控制字元。"},
    director_copy={en="Duplicate",["zh-cn"]="复制",["zh-tw"]="複製"},
    director_copy_suffix={en=" copy",["zh-cn"]=" 副本",["zh-tw"]=" 副本"},
    director_delete={en="Delete",["zh-cn"]="删除",["zh-tw"]="刪除"},
    director_confirm_delete={en="Click again to delete",["zh-cn"]="再次点击确认删除",["zh-tw"]="再次點選確認刪除"},
    director_referenced={en="Used by %d deployment rules. Remove those rules before deleting this formation.",["zh-cn"]="被 %d 条投放引用；删除编队前须先删除关联规则。",["zh-tw"]="被 %d 條投放引用；刪除編隊前須先刪除關聯規則。"},
    director_family_hordes={en="Horde group",["zh-cn"]="尸潮敌群",["zh-tw"]="屍潮敵群"},
    director_family_trickle={en="Trickle group",["zh-cn"]="小股敌群",["zh-tw"]="小股敵群"},
    director_family_specials={en="Specialist group",["zh-cn"]="特感编队",["zh-tw"]="特感編隊"},
    director_family_monsters={en="Monster group",["zh-cn"]="怪物编队",["zh-tw"]="怪物編隊"},
    director_family_patrols={en="Patrol group",["zh-cn"]="巡逻编队",["zh-tw"]="巡邏編隊"},
    director_formation_help={en="One encounter draws one variant by weight. Member ranges are counts, not chances. Each deployment controls its own schedule.",["zh-cn"]="每次遭遇按权重抽取一个变体。成员范围表示人数，不是概率；每条投放规则分别控制到场时机。",["zh-tw"]="每次遭遇按權重抽取一個變體。成員範圍表示人數，不是機率；每條投放規則分別控制到場時機。"},
    director_variant={en="Variant %d · weight %.3g",["zh-cn"]="变体 %d · 权重 %.3g",["zh-tw"]="變體 %d · 權重 %.3g"},
    director_add_variant={en="Add variant",["zh-cn"]="增加变体",["zh-tw"]="增加變體"},
    director_delete_variant={en="Remove variant",["zh-cn"]="删除变体",["zh-tw"]="刪除變體"},
    director_variant_weight={en="Variant selection weight",["zh-cn"]="变体抽取权重",["zh-tw"]="變體抽取權重"},
    director_add_member={en="Add member type",["zh-cn"]="增加成员兵种",["zh-tw"]="增加成員兵種"},
    director_min_count={en="Min. count",["zh-cn"]="人数下限",["zh-tw"]="人數下限"},
    director_max_count={en="Max. count",["zh-cn"]="人数上限",["zh-tw"]="人數上限"},
    director_formation_limits={en="Per variant: 300 ordinary troops, 16 specialists or 3 monsters. Runtime admission may reduce or delay the planned force.",["zh-cn"]="每个变体最多 300 名普通敌人、16 名特感或 3 只怪物。运行时的容量和选点限制可能缩减或延后到场。",["zh-tw"]="每個變體最多 300 名普通敵人、16 名特感或 3 只怪物。執行時的容量和選點限制可能縮減或延後到場。"},
    director_formation_immutable={en="Category: %s · create another formation to use a different category",["zh-cn"]="类别：%s · 更换类别请创建另一编队",["zh-tw"]="類別：%s · 更換類別請建立另一編隊"},
    director_rule_enabled={en="Enable this rule",["zh-cn"]="启用这条规则",["zh-tw"]="啟用這條規則"},
    director_formation_ref={en="Formation to deploy",["zh-cn"]="调用的编队",["zh-tw"]="呼叫的編隊"},
    director_timing={en="When to arrive",["zh-cn"]="到场时机",["zh-tw"]="到場時機"},
    director_conditions={en="Additional conditions",["zh-cn"]="附加条件",["zh-tw"]="附加條件"},
    director_quotas={en="Limits & selection",["zh-cn"]="额度与竞争",["zh-tw"]="額度與競爭"},
    director_inheritance={en="HCM linkage",["zh-cn"]="HCM 联动",["zh-tw"]="HCM 聯動"},
    director_trigger={en="Trigger type",["zh-cn"]="触发方式",["zh-tw"]="觸發方式"},
    director_timer={en="Elapsed time",["zh-cn"]="经过时间",["zh-tw"]="經過時間"},
    director_progress={en="Forward progress",["zh-cn"]="向前推进",["zh-tw"]="向前推進"},
    director_condition={en="Condition becomes true",["zh-cn"]="条件由不满足变为满足",["zh-tw"]="條件由不滿足變為滿足"},
    director_first_delay={en="Earliest arrival after mission start (s)",["zh-cn"]="开局后最早到场时间（秒）",["zh-tw"]="開局後最早到場時間（秒）"},
    director_interval_min={en="Minimum interval (s)",["zh-cn"]="再次投放最短间隔（秒）",["zh-tw"]="再次投放最短間隔（秒）"},
    director_interval_max={en="Maximum interval (s)",["zh-cn"]="再次投放最长间隔（秒）",["zh-tw"]="再次投放最長間隔（秒）"},
    director_progress_start={en="First trigger at progress (m)",["zh-cn"]="首次触发的推进距离（米）",["zh-tw"]="首次觸發的推進距離（米）"},
    director_progress_step={en="Further travel for another arrival (m)",["zh-cn"]="再次投放所需继续推进距离（米）",["zh-tw"]="再次投放所需繼續推進距離（米）"},
    director_start_time={en="Window opens after (s)",["zh-cn"]="有效窗口开始时间（秒）",["zh-tw"]="有效視窗開始時間（秒）"},
    director_end_time={en="Window closes after (s); 0 = no end",["zh-cn"]="有效窗口结束时间（秒）；0 为不限",["zh-tw"]="有效視窗結束時間（秒）；0 為不限"},
    director_waves={en="Waves in one encounter",["zh-cn"]="一次遭遇的波数",["zh-tw"]="一次遭遇的波數"},
    director_wave_gap={en="Gap between waves (s)",["zh-cn"]="波间等待（秒）",["zh-tw"]="波間等待（秒）"},
    director_timing_help={en="Intervals begin after the first accepted member. A condition trigger fires once while its conditions stay true; they must become false before it can fire again.",["zh-cn"]="再次投放的间隔从首名成员被接纳后开始计算。条件触发在持续满足期间只执行一次，必须先变为不满足才能重新触发。",["zh-tw"]="再次投放的間隔從首名成員被接納後開始計算。條件觸發在持續滿足期間只執行一次，必須先變為不滿足才能重新觸發。"},
    director_match={en="Combine conditions",["zh-cn"]="组合条件",["zh-tw"]="組合條件"},
    director_all={en="All must pass",["zh-cn"]="全部满足",["zh-tw"]="全部滿足"},
    director_any_match={en="At least one must pass",["zh-cn"]="任意一项满足",["zh-tw"]="任意一項滿足"},
    director_add_condition={en="Add a condition",["zh-cn"]="增加条件",["zh-tw"]="增加條件"},
    director_no_conditions={en="No extra conditions. Native permissions and the director limits still apply.",["zh-cn"]="没有额外条件；原版许可与导演全局限制仍然生效。",["zh-tw"]="沒有額外條件；原版許可與導演全侷限制仍然生效。"},
    director_condition_help={en="Native slots already accepted keep their lifecycle. Director limits still apply while HED members wait; expired requests do not pile up.",["zh-cn"]="已被原版槽位接纳的特感沿用原版流程。HED 成员等待时仍受导演全局限制；过期请求不会积压补发。",["zh-tw"]="已被原版槽位接納的特感沿用原版流程。HED 成員等待時仍受導演全侷限制；過期請求不會積壓補發。"},
    director_cooldown={en="Minimum cooldown after arrival (s)",["zh-cn"]="成功到场后的最短冷却（秒）",["zh-tw"]="成功到場後的最短冷卻（秒）"},
    director_max_occurrences={en="Mission quota; 0 = unlimited",["zh-cn"]="整局成功遭遇额度；0 为不限",["zh-tw"]="整局成功遭遇額度；0 為不限"},
    director_max_alive={en="Active encounters for this rule",["zh-cn"]="本规则同时活跃遭遇上限",["zh-tw"]="本規則同時活躍遭遇上限"},
    director_rule_priority={en="Priority; higher goes first",["zh-cn"]="优先级；数值越高越优先",["zh-tw"]="優先順序；數值越高越優先"},
    director_weight={en="Selection weight",["zh-cn"]="竞争抽取权重",["zh-tw"]="競爭抽取權重"},
    director_phase={en="Required HED phase",["zh-cn"]="要求的 HED 阶段",["zh-tw"]="要求的 HED 階段"},
    director_quota_help={en="The quota counts encounters with at least one accepted member. It is separate from enemy count, wave count and concurrent encounters. Fixed priority can delay lower-priority rules.",["zh-cn"]="额度统计至少已有一名成员被接纳的遭遇，与人数、波数及同时活跃遭遇数分别计算。固定优先级可能使低优先级规则持续等待。",["zh-tw"]="額度統計至少已有一名成員被接納的遭遇，與人數、波數及同時活躍遭遇數分別計算。固定優先順序可能使低優先順序規則持續等待。"},
    director_inherit_size={en="Follow HCM member multipliers",["zh-cn"]="跟随 HCM 的成员人数倍率",["zh-tw"]="跟隨 HCM 的成員人數倍率"},
    director_inherit_frequency={en="Follow HCM arrival frequency",["zh-cn"]="跟随 HCM 的触发频率",["zh-tw"]="跟隨 HCM 的觸發頻率"},
    director_size_multiplier={en="Additional member multiplier",["zh-cn"]="在此基础上的人数倍率",["zh-tw"]="在此基礎上的人數倍率"},
    director_frequency_multiplier={en="Additional frequency multiplier",["zh-cn"]="在此基础上的频率倍率",["zh-tw"]="在此基礎上的頻率倍率"},
    director_inherit_help={en="Common horde/trickle members follow their HCM size setting; elites follow Elite members per group. Specialists follow slot capacity; monsters follow encounter count. Patrol ordinary members stay at 1×. Custom waves remain explicit.",["zh-cn"]="普通尸潮／小股成员跟随各自的 HCM 人数倍率，精英跟随敌群精英人数。特感跟随并行容量，怪物跟随遭遇数；巡逻普通成员保持 1×。自定义波数始终由本规则指定。",["zh-tw"]="普通屍潮／小股成員跟隨各自的 HCM 人數倍率，精英跟隨敵群精英人數。特感跟隨並行容量，怪物跟隨遭遇數；巡邏普通成員保持 1×。自定義波數始終由本規則指定。"},
    director_frequency_help={en="Horde, trickle and specialist rules follow the matching HCM frequency. Other categories start at 1×. Higher frequency shortens later time or distance intervals; first-arrival and cooldown values stay explicit.",["zh-cn"]="尸潮、小股潮、特感分别跟随对应的 HCM 频率，其他类别从 1× 开始。频率越高，再次投放的时间或距离间隔越短；首次时间与冷却仍使用本规则的明确值。",["zh-tw"]="屍潮、小股潮、特感分別跟隨對應的 HCM 頻率，其他類別從 1× 開始。頻率越高，再次投放的時間或距離間隔越短；首次時間與冷卻仍使用本規則的明確值。"},
    director_budget_help={en="Each HED encounter is bounded to 256 ordinary troops, 16 specialists or 3 monsters across all waves. Native specialist slots and available locations may further limit arrivals.",["zh-cn"]="每次 HED 遭遇的所有波次合计最多 256 名普通敌人、16 名特感或 3 只怪物。原版特感槽位及出生位置仍可能进一步限制到场。",["zh-tw"]="每次 HED 遭遇的所有波次合計最多 256 名普通敵人、16 名特感或 3 只怪物。原版特感槽位及出生位置仍可能進一步限制到場。"},
    director_changed={en="Edited values",["zh-cn"]="已修改的设置",["zh-tw"]="已修改的設定"},
    director_no_changes={en="No native overrides yet. HCM values are inherited.",["zh-cn"]="尚未覆盖原版字段，当前跟随 HCM。",["zh-tw"]="尚未覆蓋原版欄位，當前跟隨 HCM。"},
    director_value_mode={en="How this value is applied",["zh-cn"]="此值的应用方式",["zh-tw"]="此值的應用方式"},
    director_follow={en="Follow HCM",["zh-cn"]="跟随 HCM",["zh-tw"]="跟隨 HCM"},
    director_fixed={en="Use a fixed value",["zh-cn"]="使用固定值",["zh-tw"]="使用固定值"},
    director_relative={en="Multiply the HCM value",["zh-cn"]="在 HCM 结果上乘倍率",["zh-tw"]="在 HCM 結果上乘倍率"},
    director_original={en="Original: %s",["zh-cn"]="原版：%s",["zh-tw"]="原版：%s"},
    director_coarse_value={en="After HCM: %s",["zh-cn"]="HCM 后：%s",["zh-tw"]="HCM 後：%s"},
    director_effective={en="HED template result: %s",["zh-cn"]="HED 模板结果：%s",["zh-tw"]="HED 模板結果：%s"},
    director_factor={en="Additional value multiplier",["zh-cn"]="额外数值倍率",["zh-tw"]="額外數值倍率"},
    director_relative_help={en="HCM is applied first, then this multiplier. The field's valid range and integer rounding still apply. Other native mission modifiers may apply afterward.",["zh-cn"]="先计算 HCM，再乘此倍率；仍受字段有效范围和整数取整约束。之后可能继续叠加原版任务修正。",["zh-tw"]="先計算 HCM，再乘此倍率；仍受欄位有效範圍和整數取整約束。之後可能繼續疊加原版任務修正。"},
    director_template_help={en="Choose the source family, then its mode and difficulty branch. Native identifiers are available in details; the numbers here are template values, not guaranteed on-screen counts.",["zh-cn"]="先选刷怪来源，再选模式与难度分支。此处编辑模板数值，不代表保证同屏人数；原版标识可在详情中查看。",["zh-tw"]="先選刷怪來源，再選模式與難度分支。此處編輯模板數值，不代表保證同屏人數；原版標識可在詳情中檢視。"},
    director_resistance={en="Resistance branch %s",["zh-cn"]="抗性档 %s",["zh-tw"]="抗性檔 %s"},
    director_challenge={en="Challenge branch %s",["zh-cn"]="挑战档 %s",["zh-tw"]="挑戰檔 %s"},
    director_branch={en="Branch %s",["zh-cn"]="分支 %s",["zh-tw"]="分支 %s"},
    director_technical={en="Show native identifiers",["zh-cn"]="显示原版标识",["zh-tw"]="顯示原版標識"},
    director_all_fields={en="All fields",["zh-cn"]="全部字段",["zh-tw"]="全部欄位"},
    director_common_fields={en="Common controls",["zh-cn"]="常用参数",["zh-tw"]="常用引數"},
    director_modified_fields={en="Edited fields",["zh-cn"]="已修改",["zh-tw"]="已修改"},
    director_legacy_field={en="No active consumer was confirmed for this field in the audited game version. It is excluded from common controls; editing it may have no effect.",["zh-cn"]="在已核对的游戏版本中，未确认这个字段的实际读取位置。常用参数已排除它；修改可能不产生效果。",["zh-tw"]="在已核對的遊戲版本中，未確認這個欄位的實際讀取位置。常用引數已排除它；修改可能不產生效果。"},
    director_reset_native={en="Remove all native overrides",["zh-cn"]="清除全部原版覆盖",["zh-tw"]="清除全部原版覆蓋"},
    director_reset_native_confirm={en="Click again: remove native overrides",["zh-cn"]="再次点击：清除全部原版覆盖",["zh-tw"]="再次點選：清除全部原版覆蓋"},
    director_summary_help={en="Presets include HCM values and condition-event seed, native overrides, formations, deployment rules and both HED seed switches. Older version 2/3 files remain readable.",["zh-cn"]="方案包含 HCM 数值和词条事件种子、原生覆盖、编队、部署规则及 HED 的两组种子开关；仍可读取旧版 2／3 文件。",["zh-tw"]="方案包含 HCM 數值和詞條事件種子、原生覆蓋、編隊、部署規則及 HED 的兩組種子開關；仍可讀取舊版 2／3 檔案。"},
    director_enabled_rules={en="%d of %d deployment rules enabled",["zh-cn"]="已启用 %d / %d 条投放规则",["zh-tw"]="已啟用 %d / %d 條投放規則"},
    director_unreferenced={en="%d formations have no deployment rule",["zh-cn"]="%d 个编队尚未被投放规则调用",["zh-tw"]="%d 個編隊尚未被投放規則呼叫"},
    director_save_failed={en="The change was not saved: %s",["zh-cn"]="修改未保存：%s",["zh-tw"]="修改未儲存：%s"},
    director_scope_off={en="Extra director is currently off",["zh-cn"]="额外编队导演当前关闭",["zh-tw"]="額外編隊導演當前關閉"},
    director_scope_on={en="Extra director will run next mission",["zh-cn"]="额外编队导演将在下一局运行",["zh-tw"]="額外編隊導演將在下一局執行"},
    director_breed_chaos_armored_infected={en="Armoured Groaner",["zh-cn"]="披甲呻吟者",["zh-tw"]="披甲呻吟者"},
    director_breed_chaos_lesser_mutated_poxwalker={en="Mutated Poxwalker",["zh-cn"]="变异瘟疫行者",["zh-tw"]="變異瘟疫行者"},
    director_breed_chaos_mutated_poxwalker={en="Tentacled Poxwalker",["zh-cn"]="触手瘟疫行者",["zh-tw"]="觸手瘟疫行者"},
    director_breed_chaos_newly_infected={en="Groaner",["zh-cn"]="呻吟者",["zh-tw"]="呻吟者"},
    director_breed_chaos_poxwalker={en="Poxwalker",["zh-cn"]="瘟疫行者",["zh-tw"]="瘟疫行者"},
    director_breed_chaos_ogryn_bulwark={en="Bulwark",["zh-cn"]="堡垒",["zh-tw"]="堡壘"},
    director_breed_chaos_ogryn_executor={en="Crusher",["zh-cn"]="粉碎者",["zh-tw"]="粉碎者"},
    director_breed_chaos_ogryn_gunner={en="Reaper",["zh-cn"]="收割者",["zh-tw"]="收割者"},
    director_breed_chaos_beast_of_nurgle={en="Beast of Nurgle",["zh-cn"]="纳垢兽",["zh-tw"]="納垢獸"},
    director_breed_chaos_plague_ogryn={en="Plague Ogryn",["zh-cn"]="瘟疫欧格林",["zh-tw"]="瘟疫歐格林"},
    director_breed_chaos_spawn={en="Chaos Spawn",["zh-cn"]="混沌魔物",["zh-tw"]="混沌魔物"},
    director_breed_chaos_hound={en="Pox Hound",["zh-cn"]="瘟疫猎犬",["zh-tw"]="瘟疫獵犬"},
    director_breed_chaos_armored_hound={en="Armoured Hound",["zh-cn"]="披甲猎犬",["zh-tw"]="披甲獵犬"},
    director_breed_chaos_poxwalker_bomber={en="Poxburster",["zh-cn"]="瘟疫爆炸者",["zh-tw"]="瘟疫爆炸者"},
    director_breed_cultist_assault={en="Dreg Stalker",["zh-cn"]="渣滓潜行者",["zh-tw"]="渣滓潛行者"},
    director_breed_cultist_melee={en="Dreg Bruiser",["zh-cn"]="渣滓格斗兵",["zh-tw"]="渣滓格鬥兵"},
    director_breed_cultist_vanguard={en="Dreg Vanguard",["zh-cn"]="渣滓先锋",["zh-tw"]="渣滓先鋒"},
    director_breed_cultist_berzerker={en="Dreg Rager",["zh-cn"]="渣滓狂战士",["zh-tw"]="渣滓狂戰士"},
    director_breed_cultist_flamer={en="Dreg Tox Flamer",["zh-cn"]="渣滓毒焰喷射手",["zh-tw"]="渣滓毒焰噴射手"},
    director_breed_cultist_grenadier={en="Dreg Tox Bomber",["zh-cn"]="渣滓毒爆投弹手",["zh-tw"]="渣滓毒爆投彈手"},
    director_breed_cultist_gunner={en="Dreg Gunner",["zh-cn"]="渣滓机枪手",["zh-tw"]="渣滓機槍手"},
    director_breed_cultist_mutant={en="Mutant",["zh-cn"]="变种人",["zh-tw"]="變種人"},
    director_breed_cultist_mutant_mutator={en="Mutant (condition variant)",["zh-cn"]="变种人（词条变体）",["zh-tw"]="變種人（詞條變體）"},
    director_breed_cultist_shocktrooper={en="Dreg Shotgunner",["zh-cn"]="渣滓霰弹枪兵",["zh-tw"]="渣滓霰彈槍兵"},
    director_breed_renegade_assault={en="Scab Stalker",["zh-cn"]="血痂潜行者",["zh-tw"]="血痂潛行者"},
    director_breed_renegade_melee={en="Scab Bruiser",["zh-cn"]="血痂格斗兵",["zh-tw"]="血痂格鬥兵"},
    director_breed_renegade_rifleman={en="Scab Shooter",["zh-cn"]="血痂射手",["zh-tw"]="血痂射手"},
    director_breed_renegade_vanguard={en="Scab Vanguard",["zh-cn"]="血痂先锋",["zh-tw"]="血痂先鋒"},
    director_breed_renegade_berzerker={en="Scab Rager",["zh-cn"]="血痂狂战士",["zh-tw"]="血痂狂戰士"},
    director_breed_renegade_executor={en="Scab Mauler",["zh-cn"]="血痂重锤兵",["zh-tw"]="血痂重錘兵"},
    director_breed_renegade_flamer={en="Scab Flamer",["zh-cn"]="血痂火焰喷射手",["zh-tw"]="血痂火焰噴射手"},
    director_breed_renegade_grenadier={en="Scab Bomber",["zh-cn"]="血痂投弹手",["zh-tw"]="血痂投彈手"},
    director_breed_renegade_gunner={en="Scab Gunner",["zh-cn"]="血痂机枪手",["zh-tw"]="血痂機槍手"},
    director_breed_renegade_netgunner={en="Scab Trapper",["zh-cn"]="血痂陷阱手",["zh-tw"]="血痂陷阱手"},
    director_breed_renegade_plasma_gunner={en="Scab Plasma Gunner",["zh-cn"]="血痂等离子枪手",["zh-tw"]="血痂等離子槍手"},
    director_breed_renegade_radio_operator={en="Scab Radio Operator",["zh-cn"]="血痂通讯兵",["zh-tw"]="血痂通訊兵"},
    director_breed_renegade_shocktrooper={en="Scab Shotgunner",["zh-cn"]="血痂霰弹枪兵",["zh-tw"]="血痂霰彈槍兵"},
    director_breed_renegade_sniper={en="Scab Sniper",["zh-cn"]="血痂狙击手",["zh-tw"]="血痂狙擊手"},
    director_native_default={en="Standard missions",["zh-cn"]="常规任务",["zh-tw"]="常規任務"},
    director_native_havoc={en="Havoc",["zh-cn"]="浩劫",["zh-tw"]="浩劫"},
    director_native_expedition={en="Expeditions",["zh-cn"]="远征",["zh-tw"]="遠征"},
    director_native_terror_events_only={en="Mission events only",["zh-cn"]="仅任务事件",["zh-tw"]="僅任務事件"},
    director_native_mutator_horde={en="Condition horde",["zh-cn"]="词条尸潮",["zh-tw"]="詞條屍潮"},
    director_native_dummy_auto_event_template={en="Placeholder event",["zh-cn"]="占位事件",["zh-tw"]="佔位事件"},
    director_native_live_event_endless_hordes_auto_event_template={en="Endless-horde activity",["zh-cn"]="无尽尸潮活动",["zh-tw"]="無盡屍潮活動"},
    director_native_live_event_saints_auto_event_template={en="Saints activity",["zh-cn"]="圣徒活动",["zh-tw"]="聖徒活動"},
    director_native_live_event_skulls_guns_auto_event_template={en="Skulls activity",["zh-cn"]="颅骨活动",["zh-tw"]="顱骨活動"},
    director_common_hint={en="Common controls are shown first. Use All fields to inspect the complete supported template tree.",["zh-cn"]="默认显示常用参数；切换全部字段可查看受支持的完整模板结构。",["zh-tw"]="預設顯示常用引數；切換全部欄位可檢視受支援的完整模板結構。"},
    director_group_fallback={en="Settings group %s",["zh-cn"]="设置分组 %s",["zh-tw"]="設定分組 %s"},
    director_branch_count={en="%s · %d fields",["zh-cn"]="%s · %d 项参数",["zh-tw"]="%s · %d 項引數"},
    director_scope_pacing={en="Global pacing selects combat stages and which sources may run. Combat load uses breed threat ratings; tension and expedition heat are separate measures.",["zh-cn"]="全局节奏决定战斗阶段及允许的刷怪来源。战斗负担由兵种威胁评分累加，紧张值与远征热度是另外两套量。",["zh-tw"]="全域性節奏決定戰鬥階段及允許的刷怪來源。戰鬥負擔由兵種威脅評分累加，緊張值與遠征熱度是另外兩套量。"},
    director_scope_roamers={en="Roamers are planned by route zones, density, pack selection and per-breed limits. Repeated members are part of a pack's composition, not a probability.",["zh-cn"]="驻军按路线分区、密度、敌群抽取和兵种限制预先布置。敌群内重复的成员表示编成数量，不是兵种抽取概率。",["zh-tw"]="駐軍按路線分割槽、密度、敵群抽取和兵種限制預先佈置。敵群內重複的成員表示編成數量，不是兵種抽取機率。"},
    director_scope_hordes={en="Hordes combine trigger time or travel, waves, compositions and spawn methods. Member count, wave count and active encounters are separate controls.",["zh-cn"]="尸潮由触发时间或推进距离、波数、编成和出生方式共同组成。成员人数、波数、同时活跃遭遇数分别控制。",["zh-tw"]="屍潮由觸發時間或推進距離、波數、編成和出生方式共同組成。成員人數、波數、同時活躍遭遇數分別控制。"},
    director_scope_specials={en="Specialists refill slots after completion. Capacity, refill time, same-breed limits and coordinated attacks are separate. Some templates use travel instead of seconds.",["zh-cn"]="特感使用结束后补充的槽位。容量、补充间隔、同类限制与协同攻击分别控制；部分模板用推进距离替代秒数。",["zh-tw"]="特感使用結束後補充的槽位。容量、補充間隔、同類限制與協同攻擊分別控制；部分模板用推進距離替代秒數。"},
    director_scope_monsters={en="Route monsters use a mission allowance and usable map sections. Scripted bosses and specialist monster replacements are separate.",["zh-cn"]="沿途怪物根据整局额度与可用地图分区安排，与任务脚本 Boss 和特感替换的怪物分别计算。",["zh-tw"]="沿途怪物根據整局額度與可用地圖分割槽安排，與任務指令碼 Boss 和特感替換的怪物分別計算。"},
    director_scope_events={en="Automatic events spend points on enemy categories. Category weights affect budget allocation, not the final percentage of each breed.",["zh-cn"]="自动事件按点数预算安排敌人类别。类别权重影响预算分配，并不直接等于最终人数占比。",["zh-tw"]="自動事件按點數預算安排敵人類別。類別權重影響預算分配，並不直接等於最終人數佔比。"},
    director_scope_mission_events={en="Mission events are scripted node sequences. Combat nodes spend points or spawn a named breed. Objective flow continues to follow the mission script.",["zh-cn"]="任务事件是按顺序执行的节点。战斗节点可按点数或指定兵种生成；任务时序与目标流程仍由任务脚本控制。",["zh-tw"]="任務事件是按順序執行的節點。戰鬥節點可按點數或指定兵種生成；任務時序與目標流程仍由任務指令碼控制。"},
    director_scope_mutators={en="Condition templates apply only while that condition is active. Pacing multipliers, extra encounters and enemy buffs are different settings.",["zh-cn"]="词条模板只在对应词条生效时参与运行。节奏倍率、额外遭遇和敌人增益是不同类型的设置。",["zh-tw"]="詞條模板只在對應詞條生效時參與執行。節奏倍率、額外遭遇和敵人增益是不同型別的設定。"},
    director_template_sources={en="These are template inputs. Difficulty, active conditions and runtime admission can still alter the final result.",["zh-cn"]="这些数值是模板输入；难度、已选词条与运行时接纳条件仍可能影响最终结果。",["zh-tw"]="這些數值是模板輸入；難度、已選詞條與執行時接納條件仍可能影響最終結果。"},
    director_group_state_settings={en="Combat stages",["zh-cn"]="战斗阶段",["zh-tw"]="戰鬥階段"},
    director_group_combat_state_settings={en="Enemy alert states",["zh-cn"]="敌人警觉状态",["zh-tw"]="敵人警覺狀態"},
    director_group_heat_settings={en="Heat stages",["zh-cn"]="热度阶段",["zh-tw"]="熱度階段"},
    director_group_challenge_rating_thresholds={en="Combat-load gates",["zh-cn"]="战斗负担门槛",["zh-tw"]="戰鬥負擔門檻"},
    director_group_allowed_spawn_types={en="Permitted spawn sources",["zh-cn"]="允许的刷怪来源",["zh-tw"]="允許的刷怪來源"},
    director_group_horde_compositions={en="Horde member lists",["zh-cn"]="尸潮成员编成",["zh-tw"]="屍潮成員編成"},
    director_group_trickle_horde_compositions={en="Trickle member lists",["zh-cn"]="小股潮成员编成",["zh-tw"]="小股潮成員編成"},
    director_group_composition={en="Event composition",["zh-cn"]="事件编成",["zh-tw"]="事件編成"},
    director_group_breeds={en="Enemy members / candidates",["zh-cn"]="敌人成员／候选",["zh-tw"]="敵人成員／候選"},
    director_group_density_settings={en="Zone populations",["zh-cn"]="区域人数",["zh-tw"]="區域人數"},
    director_group_density_order={en="Zone sequence",["zh-cn"]="区域顺序",["zh-tw"]="區域順序"},
    director_group_density_order_overrides={en="Zone sequence overrides",["zh-cn"]="区域顺序覆盖",["zh-tw"]="區域順序覆蓋"},
    director_group_pack_weights={en="Pack selection weights",["zh-cn"]="敌群抽取权重",["zh-tw"]="敵群抽取權重"},
    director_group_packs={en="Roamer packs",["zh-cn"]="驻军敌群",["zh-tw"]="駐軍敵群"},
    director_group_roamer_packs={en="Roamer packs",["zh-cn"]="驻军敌群",["zh-tw"]="駐軍敵群"},
    director_group_breed_limits={en="Breed limits",["zh-cn"]="兵种额度",["zh-tw"]="兵種額度"},
    director_group_tag_limits={en="Tag limits",["zh-cn"]="类别额度",["zh-tw"]="類別額度"},
    director_group_faction_breed_lists={en="Faction enemies",["zh-cn"]="阵营敌人",["zh-tw"]="陣營敵人"},
    director_group_faction_zone_length={en="Faction segment length",["zh-cn"]="阵营区域长度",["zh-tw"]="陣營區域長度"},
    director_group_coordinated_horde_strike_settings={en="Coordinated attacks",["zh-cn"]="协同攻势",["zh-tw"]="協同攻勢"},
    director_group_coordinated_strike_breeds={en="Coordinated specialist candidates",["zh-cn"]="协同特感候选",["zh-tw"]="協同特感候選"},
    director_group_ramp_modifiers={en="Escalation rates",["zh-cn"]="持续加压倍率",["zh-tw"]="持續加壓倍率"},
    director_group_ramp_up_states={en="Escalation stages",["zh-cn"]="加压阶段",["zh-tw"]="加壓階段"},
    director_group_factions={en="Faction choices",["zh-cn"]="阵营选择",["zh-tw"]="陣營選擇"},
    director_group_renegade={en="Scabs",["zh-cn"]="血痂",["zh-tw"]="血痂"},
    director_group_cultist={en="Dregs",["zh-cn"]="渣滓",["zh-tw"]="渣滓"},
    director_group_chaos={en="Chaos enemies",["zh-cn"]="混沌敌人",["zh-tw"]="混沌敵人"},
    director_group_none={en="Base / none",["zh-cn"]="基础／无",["zh-tw"]="基礎／無"},
    director_group_low={en="Low",["zh-cn"]="低档",["zh-tw"]="低檔"},
    director_group_high={en="High",["zh-cn"]="高档",["zh-tw"]="高檔"},
    director_group_medium={en="Medium",["zh-cn"]="中档",["zh-tw"]="中檔"},
    director_group_poxwalkers={en="Poxwalkers",["zh-cn"]="瘟疫行者",["zh-tw"]="瘟疫行者"},
    director_group_waiting_for_ramp_clear={en="Waiting for escalation to clear",["zh-cn"]="等待加压敌群清场",["zh-tw"]="等待加壓敵群清場"},
    director_group_undetected={en="Undetected",["zh-cn"]="未被发现",["zh-tw"]="未被發現"},
    director_group_detected={en="Detected",["zh-cn"]="已被发现",["zh-tw"]="已被發現"},
    director_group_alert={en="Alert",["zh-cn"]="警戒",["zh-tw"]="警戒"},
    director_group_max={en="Maximum",["zh-cn"]="最高档",["zh-tw"]="最高檔"},
    director_group_build_up_tension_low={en="Low build-up",["zh-cn"]="低压推进",["zh-tw"]="低壓推進"},
    director_group_build_up_tension={en="Build-up",["zh-cn"]="逐步升压",["zh-tw"]="逐步升壓"},
    director_group_build_up_tension_high={en="High build-up",["zh-cn"]="强力升压",["zh-tw"]="強力升壓"},
    director_group_sustain_tension_peak={en="Hold peak",["zh-cn"]="维持高峰",["zh-tw"]="維持高峰"},
    director_group_tension_peak_fade={en="Peak fades",["zh-cn"]="高峰消退",["zh-tw"]="高峰消退"},
    director_group_relax={en="Recovery",["zh-cn"]="恢复",["zh-tw"]="恢復"},
    director_group_ambush_horde={en="Ambush horde",["zh-cn"]="伏击尸潮",["zh-tw"]="伏擊屍潮"},
    director_group_far_vector_horde={en="Distant horde",["zh-cn"]="远端尸潮",["zh-tw"]="遠端屍潮"},
    director_group_far_distance_horde={en="Long-range horde",["zh-cn"]="长距尸潮",["zh-tw"]="長距屍潮"},
    director_group_flood_horde={en="Continuous flood",["zh-cn"]="持续涌入",["zh-tw"]="持續湧入"},
    director_group_trickle_horde={en="Trickle wave",["zh-cn"]="小股潮",["zh-tw"]="小股潮"},
    director_group_all={en="All candidates",["zh-cn"]="全部候选",["zh-tw"]="全部候選"},
    director_group_disablers={en="Disabling specialists",["zh-cn"]="控制型特感",["zh-tw"]="控制型特感"},
    director_group_scramblers={en="Disrupting specialists",["zh-cn"]="干扰型特感",["zh-tw"]="干擾型特感"},
    director_group_monsters={en="Monsters",["zh-cn"]="怪物",["zh-tw"]="怪物"},
    director_group_hordes={en="Hordes",["zh-cn"]="尸潮",["zh-tw"]="屍潮"},
    director_group_specials={en="Specialists",["zh-cn"]="特感",["zh-tw"]="特感"},
    director_group_roamers={en="Roamers",["zh-cn"]="驻军",["zh-tw"]="駐軍"},
    director_group_auto_events={en="Automatic events",["zh-cn"]="自动事件",["zh-tw"]="自動事件"},
    director_group_conditions={en="Required conditions",["zh-cn"]="必要条件",["zh-tw"]="必要條件"},
    director_group_high_chance_conditions={en="Higher-chance conditions",["zh-cn"]="提高概率的条件",["zh-tw"]="提高機率的條件"},
    director_group_left={en="Left",["zh-cn"]="左侧",["zh-tw"]="左側"},
    director_group_right={en="Right",["zh-cn"]="右侧",["zh-tw"]="右側"},
    director_group_ahead={en="Ahead",["zh-cn"]="前方",["zh-tw"]="前方"},
    director_group_behind={en="Behind",["zh-cn"]="后方",["zh-tw"]="後方"},
    director_group_resistance_templates={en="Resistance branches",["zh-cn"]="抗性分档",["zh-tw"]="抗性分檔"},
    director_group_challenge_templates={en="Challenge branches",["zh-cn"]="挑战分档",["zh-tw"]="挑戰分檔"},
    director_group_init_modify_pacing={en="Initial pacing modifiers",["zh-cn"]="初始节奏修正",["zh-tw"]="初始節奏修正"},
    director_group_modify_pacing={en="Pacing modifiers",["zh-cn"]="节奏修正",["zh-tw"]="節奏修正"},
    director_group_extra_trickle={en="Additional trickle encounters",["zh-cn"]="额外小股潮",["zh-tw"]="額外小股潮"},
    director_group_limits={en="Population limits",["zh-cn"]="人数与类别限制",["zh-tw"]="人數與類別限制"},
    director_group_horde_setup={en="Attack wave plan",["zh-cn"]="攻势波次安排",["zh-tw"]="攻勢波次安排"},
    director_group_trickle_horde_templates={en="Additional trickle patterns",["zh-cn"]="额外小股潮模式",["zh-tw"]="額外小股潮模式"},
    director_group_faction_composition={en="Composition by faction",["zh-cn"]="按阵营分配编成",["zh-tw"]="按陣營分配編成"},
    director_group_boss_patrols={en="Elite patrol encounters",["zh-cn"]="精英巡逻遭遇",["zh-tw"]="精英巡邏遭遇"},
    director_group_breed_lists={en="Member lists",["zh-cn"]="成员编成列表",["zh-tw"]="成員編成列表"},
    director_group_melee={en="Melee enemies",["zh-cn"]="近战敌人",["zh-tw"]="近戰敵人"},
    director_group_ranged={en="Ranged enemies",["zh-cn"]="远程敌人",["zh-tw"]="遠端敵人"},
    director_group_ranged_push_from_behind={en="Ranged pressure from behind",["zh-cn"]="后方远程压迫",["zh-tw"]="後方遠端壓迫"},
    director_group_default={en="Default setup",["zh-cn"]="默认设置",["zh-tw"]="預設設定"},
    director_group_heat_stages={en="Heat stages",["zh-cn"]="热度阶段",["zh-tw"]="熱度階段"},
    director_group_spread_ambush={en="Dispersed ambush",["zh-cn"]="分散伏击",["zh-tw"]="分散伏擊"},
    director_group_ranged_trickle_forward_horde_push_from_behind={en="Ranged trickle with rear horde",["zh-cn"]="远程小股前压与后方尸潮",["zh-tw"]="遠端小股前壓與後方屍潮"},
    director_group_coordinated_special_attack={en="Linked specialist attack",["zh-cn"]="联动特感攻击",["zh-tw"]="聯動特感攻擊"},
    director_group_elite_roamer_mix_vector={en="Mixed elite and roamer attack",["zh-cn"]="精英与驻军混合攻势",["zh-tw"]="精英與駐軍混合攻勢"},
    director_group_push_from_behind={en="Rear attack",["zh-cn"]="后方攻势",["zh-tw"]="後方攻勢"},
    director_group_override_roamer_packs={en="Roamer pack replacements",["zh-cn"]="驻军敌群替换",["zh-tw"]="駐軍敵群替換"},
    director_group_ramp_up_frequency_modifiers={en="Escalation frequency factors",["zh-cn"]="持续加压频率系数",["zh-tw"]="持續加壓頻率係數"},
    director_group_sandwich={en="Attack from both directions",["zh-cn"]="前后夹击",["zh-tw"]="前後夾擊"},
    director_group_elite_coordinated_special_attack={en="Elite and specialist attack",["zh-cn"]="精英与特感协同",["zh-tw"]="精英與特感協同"},
    director_group_long_horde={en="Extended horde",["zh-cn"]="持续尸潮",["zh-tw"]="持續屍潮"},
    director_group_next_conditions={en="Conditions to advance",["zh-cn"]="进入下一阶段的条件",["zh-tw"]="進入下一階段的條件"},
    director_group_elite_sandwich_waves={en="Elite waves from both directions",["zh-cn"]="精英前后夹击波次",["zh-tw"]="精英前後夾擊波次"},
    director_group_roamer_slot_placement_settings={en="Roamer formation positions",["zh-cn"]="驻军队形位置",["zh-tw"]="駐軍隊形位置"},
    director_group_circle_placement={en="Circular formation",["zh-cn"]="环形队形",["zh-tw"]="環形隊形"},
    director_group_elite_spread_ambush={en="Dispersed elite ambush",["zh-cn"]="分散精英伏击",["zh-tw"]="分散精英伏擊"},
    director_group_override_trickle_horde_compositions={en="Trickle composition replacements",["zh-cn"]="小股潮编成替换",["zh-tw"]="小股潮編成替換"},
    director_group_trickle_horde_overrides={en="Trickle overrides",["zh-cn"]="小股潮覆盖",["zh-tw"]="小股潮覆蓋"},
    director_group_blockade_push_sandwich={en="Blockade and flank attack",["zh-cn"]="封锁推进与前后夹击",["zh-tw"]="封鎖推進與前後夾擊"},
    director_group_houndmaster_strike={en="Houndmaster attack",["zh-cn"]="训犬师攻势",["zh-tw"]="訓犬師攻勢"},
    director_group_elite_captain_ambush={en="Elite and captain ambush",["zh-cn"]="精英与队长伏击",["zh-tw"]="精英與隊長伏擊"},
    director_group_back_conditions={en="Conditions to step back",["zh-cn"]="退回上一阶段的条件",["zh-tw"]="退回上一階段的條件"},
    director_group_special_config={en="Specialist settings",["zh-cn"]="特感设置",["zh-tw"]="特感設定"},
    director_group_spawners={en="Spawn points",["zh-cn"]="出生点",["zh-tw"]="出生點"},
    director_group_template={en="Encounter settings",["zh-cn"]="遭遇设置",["zh-tw"]="遭遇設定"},
    director_group_breed_names={en="Enemy candidates",["zh-cn"]="敌人候选",["zh-tw"]="敵人候選"},
    director_group_specials_monster_spawn_config={en="Monster replacements for specialists",["zh-cn"]="特感替换怪物",["zh-tw"]="特感替換怪物"},
    director_group_terror_events={en="Mission combat events",["zh-cn"]="任务战斗事件",["zh-tw"]="任務戰鬥事件"},
    director_group_trickle_hordes={en="Trickle waves",["zh-cn"]="小股潮",["zh-tw"]="小股潮"},
    director_group_override_all_roamer_packs={en="All roamer pack replacements",["zh-cn"]="全部驻军敌群替换",["zh-tw"]="全部駐軍敵群替換"},
    director_group_flood_fill={en="Navigable formation area",["zh-cn"]="可行走队形区域",["zh-tw"]="可行走隊形區域"},
    director_group_extraction_wait_timings={en="Extraction waiting stages",["zh-cn"]="撤离等待阶段",["zh-tw"]="撤離等待階段"},
    director_group_spawn_settings={en="Spawn settings",["zh-cn"]="生成设置",["zh-tw"]="生成設定"},
    director_group_heat_lookups={en="Heat scaling tables",["zh-cn"]="热度调节表",["zh-tw"]="熱度調節表"},
    director_group_heat_stage_per_location={en="Heat by location",["zh-cn"]="各区域热度",["zh-tw"]="各區域熱度"},
    director_group_excluded_breed_tags={en="Excluded enemy categories",["zh-cn"]="排除的敌人类别",["zh-tw"]="排除的敵人類別"},
    director_group_flamer={en="Faction flamer",["zh-cn"]="当前阵营喷火兵",["zh-tw"]="當前陣營噴火兵"},
    director_group_grenadier={en="Faction bomber",["zh-cn"]="当前阵营投弹手",["zh-tw"]="當前陣營投彈手"},
    director_group_gunner={en="Faction gunner",["zh-cn"]="当前阵营机枪手",["zh-tw"]="當前陣營機槍手"},
    director_group_shotgunner={en="Faction shotgunner",["zh-cn"]="当前阵营霰弹枪兵",["zh-tw"]="當前陣營霰彈槍兵"},
    director_group_rager={en="Faction rager",["zh-cn"]="当前阵营狂战士",["zh-tw"]="當前陣營狂戰士"},
    director_recheck_conditions={en="Continue checking conditions after the first member arrives",["zh-cn"]="首名成员到场后，继续逐项检查附加条件",["zh-tw"]="首名成員到場後，繼續逐項檢查附加條件"},
    director_condition_horde_active={en="A native horde is being generated",["zh-cn"]="原版尸潮正在生成",["zh-tw"]="原版屍潮正在生成"},
    director_condition_horde_idle={en="No native horde is being generated",["zh-cn"]="当前没有原版尸潮生成",["zh-tw"]="當前沒有原版屍潮生成"},
    director_saved_invalid={en="Stored HED settings were invalid. Defaults are active; the saved data has not been overwritten.",["zh-cn"]="已保存的 HED 设置无效，当前使用默认设置；原保存数据尚未被覆盖。",["zh-tw"]="已儲存的 HED 設定無效，當前使用預設設定；原儲存資料尚未被覆蓋。"},
    director_navigation_required={en="Extra encounters need the current Havoc Condition Manager with shared navigation support. Update HCM and restart the game.",["zh-cn"]="额外编队需要带共享寻路支持的当前 HCM。请更新 HCM 并重新启动游戏。",["zh-tw"]="額外編隊需要帶共享尋路支援的當前 HCM。請更新 HCM 並重新啟動遊戲。"},
}
