return {
    template_reset={en="Reset all HED edits",["zh-cn"]="重置 HED 全部修改",["zh-tw"]="重設 HED 全部修改"},
    template_reset_confirm={en="Click again to reset HED",["zh-cn"]="再次点击以重置 HED",["zh-tw"]="再次點選以重設 HED"},
    template_reset_done={en="HED edits and map seed reset. HCM settings and saved files are kept.",["zh-cn"]="已重置 HED 修改与地图种子，保留 HCM 设置和方案文件。",["zh-tw"]="已重設 HED 修改與地圖種子，保留 HCM 設定與方案檔案。"},
    template_library={en="Templates",["zh-cn"]="模板库",["zh-tw"]="範本庫"},
    template_back={en="Back to editor",["zh-cn"]="返回精调",["zh-tw"]="返回精調"},
    template_heading={en="Player template library",["zh-cn"]="玩家模板库",["zh-tw"]="玩家範本庫"},
    template_list_title={en="Saved templates",["zh-cn"]="已保存的模板",["zh-tw"]="已儲存的範本"},
    template_selected={en="Template selected. Review it before loading.",["zh-cn"]="已选择模板，请查看摘要后加载。",["zh-tw"]="已選擇範本，請查看摘要後載入。"},
    template_name_label={en="Template name · up to 64 characters · Enter to finish, Esc to cancel editing",["zh-cn"]="模板名称 · 最多64个字符 · 回车完成，Esc取消编辑",["zh-tw"]="範本名稱 · 最多64個字元 · Enter完成，Esc取消編輯"},
    template_save={en="Save current setup",["zh-cn"]="保存当前配置",["zh-tw"]="儲存目前設定"},
    template_load={en="Load selected",["zh-cn"]="加载所选模板",["zh-tw"]="載入所選範本"},
    template_export={en="Copy share data",["zh-cn"]="复制分享内容",["zh-tw"]="複製分享內容"},
    template_import={en="Import from clipboard",["zh-cn"]="从剪贴板导入",["zh-tw"]="從剪貼簿匯入"},
    template_refresh={en="Refresh",["zh-cn"]="刷新列表",["zh-tw"]="重新整理"},
    template_delete={en="Delete selected",["zh-cn"]="删除所选",["zh-tw"]="刪除所選"},
    template_delete_title={en="Delete this saved template?",["zh-cn"]="确认删除此模板？",["zh-tw"]="確認刪除此範本？"},
    template_delete_file={en="File: %s",["zh-cn"]="文件：%s",["zh-tw"]="檔案：%s"},
    template_delete_hint={en="This permanently deletes only the named file. Your currently loaded setup will stay in place. Cancel or Esc keeps the file.",["zh-cn"]="将永久删除上述文件，当前已加载的生成器配置不会改变。点击取消或按Esc可保留文件。",["zh-tw"]="將永久刪除上述檔案，目前已載入的生成器設定不會改變。點擊取消或按Esc可保留檔案。"},
    template_delete_confirm={en="Confirm delete",["zh-cn"]="确认删除",["zh-tw"]="確認刪除"},
    template_deleted={en="Template deleted. Your current setup is unchanged.",["zh-cn"]="模板已删除，当前配置保持不变。",["zh-tw"]="範本已刪除，目前設定保持不變。"},
    template_empty={en="No templates yet. Enter a name and save your current setup, or place a shared JSON file in the template folder and refresh.",["zh-cn"]="暂无模板。输入名称保存当前配置，或将他人分享的JSON文件放入模板文件夹后刷新。",["zh-tw"]="尚無範本。輸入名稱儲存目前設定，或將他人分享的JSON檔案放入範本資料夾後重新整理。"},
    template_scope={en="Saves HCM multipliers, native field overrides, trigger rules and map seed. Uses current game templates. Mission and condition selections remain in SoloPlay.",["zh-cn"]="保存 HCM 倍率、原版字段覆盖、触发规则和地图种子；使用当前游戏模板。任务和词条选择仍由 SoloPlay 保存。",["zh-tw"]="儲存 HCM 倍率、原版欄位覆蓋、觸發規則和地圖種子；使用目前遊戲範本。任務和詞條選擇仍由 SoloPlay 儲存。"},
    template_folder_hint={en="Folder: %%APPDATA%%/Fatshark/Darktide/HavocEnemyDirector/templates\nSaved JSON files can be shared directly. Add received files here, then refresh.",["zh-cn"]="文件夹：%%APPDATA%%/Fatshark/Darktide/HavocEnemyDirector/templates\n保存的JSON文件可直接分享；收到的文件放入此处后刷新即可选择。",["zh-tw"]="資料夾：%%APPDATA%%/Fatshark/Darktide/HavocEnemyDirector/templates\n儲存的JSON檔案可直接分享；收到的檔案放入此處後重新整理即可選擇。"},
    template_folder={en="Copy template folder path",["zh-cn"]="复制模板文件夹路径",["zh-tw"]="複製範本資料夾路徑"},
    template_load_hint={en="Loading replaces HCM multipliers and HED field overrides, rules and seed. Changes apply next mission.",["zh-cn"]="加载将替换 HCM 倍率，以及 HED 字段覆盖、触发规则和种子；在下一局生效。",["zh-tw"]="載入將取代 HCM 倍率，以及 HED 欄位覆蓋、觸發規則和種子；在下一局生效。"},
    template_import_hint={en="Share data checked. You can change its name, then save the imported template. Your active setup changes only when you load it.",["zh-cn"]="分享内容已检查。可以修改名称后保存导入的模板；点击加载后才会应用到当前设置。",["zh-tw"]="分享內容已檢查。可修改名稱後儲存匯入的範本；點擊載入後才會套用至目前設定。"},
    template_overwrite_hint={en="A file with this name exists. Confirm to replace it, or use another name.",["zh-cn"]="已存在同名文件。确认后覆盖，或修改名称另存。",["zh-tw"]="已存在同名檔案。確認後覆寫，或修改名稱另存。"},
    template_confirm_load={en="Confirm load",["zh-cn"]="确认加载",["zh-tw"]="確認載入"},
    template_confirm_overwrite={en="Confirm overwrite",["zh-cn"]="确认覆盖保存",["zh-tw"]="確認覆寫儲存"},
    template_confirm_import={en="Save imported template",["zh-cn"]="保存导入模板",["zh-tw"]="儲存匯入範本"},
    template_cancel={en="Cancel",["zh-cn"]="取消",["zh-tw"]="取消"},
    template_saved={en="Template saved as a shareable JSON file.",["zh-cn"]="模板已保存为可分享的JSON文件。",["zh-tw"]="範本已儲存為可分享的JSON檔案。"},
    template_loaded={en="Template loaded. It will apply to your next mission.",["zh-cn"]="模板已加载，将在下一次任务中生效。",["zh-tw"]="範本已載入，將在下一次任務中生效。"},
    template_copied={en="Copied to clipboard.",["zh-cn"]="已复制到剪贴板。",["zh-tw"]="已複製到剪貼簿。"},
    template_name_invalid={en="Enter a name of 1–64 characters without path separators or Windows filename symbols.",["zh-cn"]="请输入1–64个字符的名称，不可含路径分隔符或Windows文件名禁用符号。",["zh-tw"]="請輸入1–64個字元的名稱，不可含路徑分隔符或Windows檔名禁用符號。"},
    template_invalid={en="Invalid template setting",["zh-cn"]="模板设置无效",["zh-tw"]="範本設定無效"},
    template_version={en="Unsupported preset format. Legacy custom-generator presets remain on disk but cannot be used by the native template editor.",["zh-cn"]="此方案格式不受支持。旧版自定义生成器方案仍保留在磁盘中，不能直接用于原版模板编辑器。",["zh-tw"]="此方案格式不受支援。舊版自訂生成器方案仍保留於磁碟，不能直接用於原版範本編輯器。"},
    template_json_invalid={en="This is not a valid template JSON file.",["zh-cn"]="内容不是有效的模板JSON。",["zh-tw"]="內容不是有效的範本JSON。"},
    template_too_large={en="The template exceeds the 256 KiB limit.",["zh-cn"]="模板超过256 KiB大小限制。",["zh-tw"]="範本超過256 KiB大小限制。"},
    template_file_invalid={en="Invalid template. Select it to see why.",["zh-cn"]="模板无效，选中后查看原因。",["zh-tw"]="範本無效，選取後查看原因。"},
    template_library_full={en="The folder has more than 256 JSON files. Move unused files out and refresh.",["zh-cn"]="文件夹中超过256个JSON文件，请移出不需要的文件后刷新。",["zh-tw"]="資料夾中超過256個JSON檔案，請移出不需要的檔案後重新整理。"},
    template_io_unavailable={en="File access is unavailable. Check Darktide Mod Loader.",["zh-cn"]="无法访问模板文件，请检查Darktide Mod Loader。",["zh-tw"]="無法存取範本檔案，請檢查Darktide Mod Loader。"},
    template_io_failed={en="Could not read or save the file. Check the template folder and its permissions.",["zh-cn"]="无法读取或保存文件，请检查模板文件夹及其权限。",["zh-tw"]="無法讀取或儲存檔案，請檢查範本資料夾及其權限。"},
    template_clipboard_unavailable={en="Clipboard access failed.",["zh-cn"]="无法读取或写入剪贴板。",["zh-tw"]="無法讀取或寫入剪貼簿。"},
    template_unit_missing={en="This game version does not contain a unit used by the template",["zh-cn"]="当前游戏版本缺少模板使用的单位",["zh-tw"]="目前遊戲版本缺少範本使用的單位"},
    template_disabled={en="Enable Havoc Condition Manager and Havoc Enemy Director first.",["zh-cn"]="请先启用 HCM 和 HED。",["zh-tw"]="請先啟用 HCM 和 HED。"},
    template_apply_failed={en="Could not apply the template. An attempt was made to restore the previous setup.",["zh-cn"]="模板应用失败，已尝试恢复原配置。",["zh-tw"]="範本套用失敗，已嘗試還原原設定。"},
}
